apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: adhd-api:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_PASSWORD
        - name: DB_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_DATABASE_NAME
        - name: DB_HOST
          value: db
        - name: DB_PORT
          value: "5432"
        ports:
        - containerPort: 8000
